### ISSUE TITLE
Refresh no longer works

### ISSUE THREAD

**Issue by Arbiter549** [joelghill/retromoonlight#1]
After installing this, the refresh function says theres an error on line two. Any help?

**Comment by manshorts** [comment]
I'm having the same problem with no luck tinkering around.

**Comment by joelghill** [comment]
Hey guys, thanks for reporting this. I'll look into the issue when I have time and hopefully I can come up with a fix.

**Comment by llamadestroyer** [comment]
> 
> 
> Hey guys, thanks for reporting this. I'll look into the issue when I have time and hopefully I can come up with a fix.

man i think u wanna look this: https://retropie.org.uk/forum/topic/19872/moonlight-request-for-comments-and-testing

it works but i cant get any art(scrape). i used your script in past... it was delicious, please do it again.

**Comment by chia591** [comment]
Any solutions yet that i have not heard about?

**Comment by joelghill** [comment]
Hey folks, I'm going to try and update soon. Stay tuned!

**Comment by StonedEdge** [comment]
Did this ever get fixed? Still seeing the error in 2022...
